[tool.poetry]
name = "aoc"
version = "2022.0.0"
description = "Attempting Advent of Code in Golang and Python."
authors = ["Brendan Cazier <cazier@github>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.testing.dependencies]
ward = "^0.67.0b0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
ipython = "^8.5.0"
black = "^22.8.0"
pudb = "^2022.1.2"
isort = "^5.10.1"
pylint = "^2.15.3"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.isort]
line_length = 119
length_sort = true
multi_line_output = 3
include_trailing_comma = true

[tool.pylint.'FORMAT']
max-line-length = 119

[tool.pylint.'MESSAGES CONTROL']
disable = "missing-module-docstring,missing-function-docstring"

[tool.mypy]
strict = true
mypy_path = "python"
show_error_codes = true
namespace_packages = true
explicit_package_bases = true

[tool.ward]
hook_module = ['utils.conftest']
