name: Test Golang Files

on:
  push:
  pull_request:

jobs:
  utilities-test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest

    steps:
      - uses: actions/checkout@v3
      - run: go test ./... -race -covermode=atomic -coverprofile=.coverage.go

  # utilities-coverage:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: golang:latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: go test ./aoclib/go/... -v

  event-2024-test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest

    steps:
      - uses: actions/checkout@v3
      - run: go test ./2024/... -v
