name: Test Python Files
defaults:
  run:
    working-directory: python

on:
  push:
    branches:
      - main
      - python

env:
  PYTHONPATH: .

jobs:
  test_utilities:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run ward test -p utils

  test_2022:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run ward test -p year2022

  coverage:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run coverage run -m ward test && poetry run coverage xml
      - uses: ./.github/actions/coverage/
        id: coverage
        with:
          coverage_file: python/coverage.xml
          secret: ${{ secrets.CODECOV_TOKEN }}
