name: Test Python Files
defaults:
  run:
    working-directory: python

on:
  push:
    branches:
      - main

env:
  PYTHONPATH: .

jobs:
  test_utilities:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run ward test -p utils

  test_2022:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only testing
      - run: poetry run ward test -p year2022

  # coverage:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: golang:latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: go test ./... -race -covermode=atomic -coverprofile=coverage.out
  #     - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
  #     - run: chmod +x codecov
  #     - run: ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage.out
