name: Test Python Files

on:
  push:
  pull_request:

jobs:
  utilities-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv python install
      - run: uv sync --all-extras --dev
      - run: uv run coverage run --data-file=.coverage.python -m pytest -v aoclib/python
      - uses: actions/upload-artifact@v4
        with:
          name: python_coverage
          path: .coverage.python
          include-hidden-files: true

  utilities-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv python install
      - run: uv sync --all-extras --dev
      - run: uv run mypy .
        working-directory: ./aoclib/python/src/aoclib

  utilities-coverage:
    needs: utilities-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/download-artifact@v4
        with:
          name: python_coverage
      - run: uv python install
      - run: uv add coverage
      - run: uv run coverage report --data-file=.coverage.python

  event-2024-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv python install
      - run: uv sync --all-extras --dev
      - run: uv run pytest -v aoc/year2024
